@startsalt
scale 1
{+
{* File | Edit | Help }
.
{/ Estudante | Outros Cadastros }
{+
.
=== Cadastro de Estudante
.
Id | "1     "
Matrícula | "123456      "
Nome Completo | "João da Silva                            "
Data de Nascimento | "11/11/2011"
.
.|{{[Novo]|[Editar]|[Deletar]|[Buscar]|[Cancelar]|[Confirmar]}}
}
==
{#
**Id        ** |**Matrícula           **|**Nome Completo                       ** |**Data de Nascimento**
1 | 123456 | João Silva | 11/11/2011
2 | 456789 | Maria Souza | 22/12/2002
. | . | . | .
. | . | . | .
. | . | . | .
. | . | . | .
. | . | . | .
}
==
Observações:
- ⇕ Entre o formulário e a tabela existe uma barra de redimensionamento (SplitPane),
permite ajustar dinamicamente o espaço na tela
}
@endsalt
